version: "3"
services:
  node-app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - ports=4000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sameer
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
    
  redis:
    image: redis

volumes:
  mongo-db: