version: "3"
services:
  node-app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - ports=4000
    # env_file:
    #   - ./.env
